spring.application.name=Chamba

# Configuración para desarrollo local (H2)
#spring.datasource.url=jdbc:h2:file:./chamba_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# PostgreSQL remoto (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7k20i8js32c73ca3go0-a.virginia-postgres.render.com:5432/chamba_db_ra94?sslmode=require
spring.datasource.username=chamba_db_ra94_user
spring.datasource.password=YT5nE5JPNd9erdF4CSMP2sVafA3e4i8S
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración común (Hibernate, logs, etc.)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Consola H2 (solo útil localmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Uploads (fotos) - funciona local y en Render
chamba.uploads.dir=./uploads/
spring.web.resources.static-locations=classpath:/static/,file:./uploads/